"""Turn the model's per-section output into one valid Beamer ``.tex`` document.

This is the load-bearing module: because ChatEKLD's ``system_prompt`` is only a
*prefix* over its answer template, the model's section output is treated as
untrusted "Beamer body" — we strip anything that does not belong inside the
document body, assemble a known-good preamble around the sections ourselves, and
run a light structural sanity check (no compiler — emit-only by design).
"""
from __future__ import annotations

import re
from dataclasses import dataclass, field
from typing import Optional

# Sentinel tokens for the preamble template. We deliberately do NOT use
# str.format / string.Template because the LaTeX body is full of ``{``/``}`` and
# ``$`` which would collide with those mini-languages.
_PREAMBLE_TEMPLATE = r"""\documentclass{beamer}
\usetheme{@@THEME@@}
\usepackage[utf8]{inputenc}
\usepackage[T1]{fontenc}
\usepackage{lmodern}

\title{@@TITLE@@}
\author{@@AUTHOR@@}
\institute{@@INSTITUTE@@}
\date{@@DATE@@}

% Generated by deckgen — grounded in the user's Obsidian vault (ChatEKLD).
% This file is emitted, not compiled. Compile it yourself, e.g.:  latexmk -pdf <file>.tex

\begin{document}

\frame{\titlepage}

\begin{frame}{Outline}
  \tableofcontents
\end{frame}

@@SECTIONS@@

\end{document}
"""

# Lines that belong to the preamble / document scaffold and must never appear
# inside a section body (we own the scaffold). Matched at line start after
# optional whitespace.
_PREAMBLE_LINE_RE = re.compile(
    r"^\s*\\(?:documentclass|usepackage|usetheme|usecolortheme|usefonttheme"
    r"|title|subtitle|author|institute|date|maketitle)\b"
)
_DOCUMENT_ENV_RE = re.compile(r"^\s*\\(?:begin|end)\{document\}")
_TITLEPAGE_RE = re.compile(r"^\s*\\frame\{\\titlepage\}")
_TOC_FRAME_HINT_RE = re.compile(r"\\tableofcontents")

# A fenced code block wrapper the model may wrap its answer in.
_FENCE_RE = re.compile(r"^\s*```[a-zA-Z]*\s*$")

_FRAME_BEGIN_RE = re.compile(r"\\begin\{frame\}")
_FRAME_END_RE = re.compile(r"\\end\{frame\}")
_SECTION_RE = re.compile(r"\\section\b")

# LaTeX macros that can execute shell commands or read/write arbitrary files at
# *compile* time. The model's output is grounded in untrusted vault notes, so a
# prompt-injection (or accident) could emit one of these; we never strip them
# (that could corrupt legitimate content) but we WARN so the user reviews the
# file and compiles without shell-escape. See validate().
_DANGEROUS_MACRO_RE = re.compile(r"\\(?:write18|immediate|openin|input|include|read)\b")

# Citation commands whose argument is a (comma-separated list of) bib key(s).
# Used by the hallucinated-key guard in validate() and is biblatex/natbib-aware.
_CITE_MACRO_RE = re.compile(
    r"\\(?:cite|citefoot|textcite|parencite|autocite|smartcite|footcite"
    r"|citeauthor|citeyear|citep|citet|citealp|citealt|citenum)\*?"
    r"(?:\[[^\]]*\])*\s*\{([^}]*)\}"
)

# Characters to escape when injecting CLI-supplied metadata into LaTeX macros.
# Order matters: backslash is not escaped (metadata is plain text and a stray
# backslash is far rarer than the listed specials); we keep this conservative.
_METADATA_ESCAPES = {
    "&": r"\&",
    "%": r"\%",
    "$": r"\$",
    "#": r"\#",
    "_": r"\_",
    "{": r"\{",
    "}": r"\}",
}


@dataclass
class DeckMeta:
    """CLI-supplied document metadata."""
    title: str
    author: str = ""
    institute: str = ""
    date: str = ""  # empty -> \today
    theme: str = "Madrid"


@dataclass
class SectionOutput:
    """One section's sanitized Beamer body plus provenance for logging."""
    title: str
    body: str
    raw: str = ""
    infos: list = field(default_factory=list)
    placeholder: bool = False  # True when no usable content was generated


def latex_escape_metadata(value: str) -> str:
    """Escape LaTeX specials in a short metadata string (title/author/...)."""
    return "".join(_METADATA_ESCAPES.get(ch, ch) for ch in value)


def sanitize_section(text: str) -> str:
    """Reduce a model answer to just the section body we will embed.

    Strips markdown code fences, drops any preamble / document-scaffold lines the
    model emitted despite instructions, and trims leading/trailing prose by
    slicing from the first ``\\section`` or ``\\begin{frame}`` to the last
    ``\\end{frame}`` when those anchors exist. Idempotent.
    """
    if not text:
        return ""

    kept: list[str] = []
    for line in text.splitlines():
        if _FENCE_RE.match(line):
            continue
        if _PREAMBLE_LINE_RE.match(line):
            continue
        if _DOCUMENT_ENV_RE.match(line):
            continue
        if _TITLEPAGE_RE.match(line):
            continue
        # A bare "\tableofcontents" frame the model duplicated: drop the
        # standalone line (we own the Outline frame). Only drop if the line is
        # essentially just the macro, to avoid eating real content.
        if _TOC_FRAME_HINT_RE.search(line) and line.strip().startswith("\\tableofcontents"):
            continue
        kept.append(line)

    body = "\n".join(kept)

    # Trim to the meaningful span if we can find anchors.
    start_candidates = [m.start() for m in (_SECTION_RE.search(body), _FRAME_BEGIN_RE.search(body)) if m]
    if start_candidates:
        start = min(start_candidates)
        last_end = None
        for m in _FRAME_END_RE.finditer(body):
            last_end = m.end()
        if last_end is not None and last_end > start:
            body = body[start:last_end]
        else:
            body = body[start:]

    body = body.strip()
    # A real section must contain at least one frame. If none survives, the model
    # returned prose or a server fallback message (e.g. "Agent did not produce a
    # final answer"), not Beamer — signal "empty" so the caller substitutes a
    # placeholder frame instead of leaking loose text into the document body.
    if not _FRAME_BEGIN_RE.search(body):
        return ""
    return body


def _sections_block(sections: list[SectionOutput]) -> str:
    """Join the non-empty sanitized section bodies, or a placeholder comment."""
    bodies = [sec.body.strip() for sec in sections if sec.body.strip()]
    return "\n\n".join(bodies) if bodies else "% (no section content generated)"


def assemble_with_template(
    sections: list[SectionOutput],
    *,
    preamble: str,
    opening: str,
    closing: str,
) -> str:
    """Assemble a deck around a user-supplied template shell.

    *preamble* / *opening* / *closing* come from
    :func:`deckgen.template.split_template`; the generated section bodies are
    injected between *opening* (title + TOC scaffold, already containing
    ``\\begin{document}``) and *closing* (the ``\\end{document}`` tail). The
    template parts are trusted (user-authored); only the section bodies are
    model output.
    """
    parts = [
        preamble.rstrip(),
        "",
        opening.rstrip(),
        "",
        _sections_block(sections),
        "",
        closing.strip(),
        "",
    ]
    return "\n".join(parts)


def extract_cite_keys(tex: str) -> list[str]:
    """Return every bib key referenced by a citation command in *tex*."""
    keys: list[str] = []
    for m in _CITE_MACRO_RE.finditer(tex):
        for raw in m.group(1).split(","):
            k = raw.strip()
            if k:
                keys.append(k)
    return keys


def assemble(sections: list[SectionOutput], meta: DeckMeta) -> str:
    """Wrap sanitized section bodies in the Beamer preamble template."""
    sections_block = _sections_block(sections)

    date = meta.date.strip()
    date_value = latex_escape_metadata(date) if date else r"\today"

    out = _PREAMBLE_TEMPLATE
    out = out.replace("@@THEME@@", meta.theme or "Madrid")
    out = out.replace("@@TITLE@@", latex_escape_metadata(meta.title))
    out = out.replace("@@AUTHOR@@", latex_escape_metadata(meta.author))
    out = out.replace("@@INSTITUTE@@", latex_escape_metadata(meta.institute))
    out = out.replace("@@DATE@@", date_value)
    out = out.replace("@@SECTIONS@@", sections_block)
    return out


def _strip_latex_comments(text: str) -> str:
    """Drop LaTeX line comments (an unescaped ``%`` to end-of-line).

    validate() must not be fooled by *commented-out* LaTeX: a ``% \\end{frame}``
    is not a real frame close, and a commented ``\\input`` / ``\\cite`` is inert.
    Counting/scanning the comment-stripped text fixes both false positives and
    false negatives. (Mirrors ``template.strip_comments``; kept local so this
    module stays dependency-free, like the rest of the deckgen core.)
    """
    out = []
    for line in text.splitlines():
        cut = None
        for i, ch in enumerate(line):
            if ch == "%" and (i == 0 or line[i - 1] != "\\"):
                cut = i
                break
        out.append(line if cut is None else line[:cut])
    return "\n".join(out)


def validate(
    tex: str,
    *,
    generated_tex: Optional[str] = None,
    known_bib_keys: Optional[set] = None,
) -> list[str]:
    """Best-effort structural checks. Returns a list of human-readable warnings.

    No LaTeX compiler is invoked (emit-only design); these catch the failures we
    can detect cheaply: unbalanced ``frame`` environments, a missing/duplicated
    ``document`` environment, and a deck with no sections.

    Structural checks run over the whole *tex*. The dangerous-macro and
    citation-key checks run over *generated_tex* when supplied (the
    model-generated section span) so the **trusted** template preamble/scaffold
    is not flagged — e.g. a legitimate ``\\input`` in the user's own preamble.
    When *generated_tex* is ``None`` the whole document is scanned (legacy
    no-template path). *known_bib_keys*, when given, enables a guard that warns
    about ``\\citefoot{key}`` / ``\\cite{key}`` keys absent from the bibliography
    (an invented citation to review before compiling).
    """
    warnings: list[str] = []
    # Strip comments before counting/scanning so a commented-out \end{frame},
    # \input or \cite is not mistaken for live LaTeX (both false negatives in
    # the frame balance and false positives in the danger/cite guards).
    scan_tex = _strip_latex_comments(tex)
    untrusted = _strip_latex_comments(tex if generated_tex is None else generated_tex)

    n_begin = len(_FRAME_BEGIN_RE.findall(scan_tex))
    n_end = len(_FRAME_END_RE.findall(scan_tex))
    if n_begin != n_end:
        warnings.append(
            f"Unbalanced frame environments: {n_begin} \\begin{{frame}} vs "
            f"{n_end} \\end{{frame}} — the deck will not compile until fixed."
        )

    n_doc_begin = len(re.findall(r"\\begin\{document\}", scan_tex))
    n_doc_end = len(re.findall(r"\\end\{document\}", scan_tex))
    if n_doc_begin != 1 or n_doc_end != 1:
        warnings.append(
            f"Expected exactly one document environment, found "
            f"{n_doc_begin} \\begin{{document}} / {n_doc_end} \\end{{document}}."
        )

    if not _SECTION_RE.search(scan_tex):
        warnings.append("No \\section found — the table of contents will be empty.")

    if n_begin == 0:
        warnings.append("No frames found — the generated deck has no slides.")

    danger = sorted(set(_DANGEROUS_MACRO_RE.findall(untrusted)))
    if danger:
        warnings.append(
            "Potentially unsafe LaTeX found in generated content: "
            f"{', '.join(danger)}. The deck is built from untrusted vault notes — "
            "review these before compiling, and compile WITHOUT shell-escape "
            "(e.g. `pdflatex -no-shell-escape`)."
        )

    if known_bib_keys is not None:
        unknown = sorted({
            k for k in extract_cite_keys(untrusted) if k not in known_bib_keys
        })
        if unknown:
            warnings.append(
                "Citation key(s) not found in the bibliography: "
                f"{', '.join(unknown)}. The model may have invented these — "
                "remove the \\citefoot/\\cite or add the entry to your .bib "
                "before compiling (an undefined key compiles to '[?]')."
            )

    return warnings
