"""Write a generated deck into a compile-ready project folder.

Given the assembled ``.tex``, an output directory and a slug, create

    <out_dir>/<slug>/<slug>.tex
    <out_dir>/<slug>/Makefile        # DOC = <slug>; include ../common/latex-build.mk

so the deck drops straight into the user's LaTeX suite and builds with ``make``.
This module stays app-independent (no project imports) — like the vendored audit
tree, it keeps its own atomic-write helper rather than importing ``core.utils``.
"""
from __future__ import annotations

import os
import re
import tempfile

# A deck folder/file name: letters, digits, and the safe separators. No slashes,
# no ``..`` — the slug names a single new child directory under out_dir.
_SLUG_RE = re.compile(r"[^A-Za-z0-9._-]+")
_SAFE_SLUG_RE = re.compile(r"\A[A-Za-z0-9][A-Za-z0-9._-]*\Z")

_MAKEFILE_TEMPLATE = (
    "# Generated by deckgen. Build with:  make view   (or: make)\n"
    "# Everything else (targets, OS-aware viewer, dated PDFs) lives in\n"
    "# common/latex-build.mk.\n"
    "DOC = {slug}\n"
    "include ../common/latex-build.mk\n"
)


class ScaffoldError(RuntimeError):
    """Raised when the deck folder cannot be created safely."""


def slugify(text: str) -> str:
    """Filesystem-safe slug: ``[A-Za-z0-9._-]``, lower-cased, never empty."""
    slug = _SLUG_RE.sub("_", (text or "").strip()).strip("_.-").lower()
    return slug or "deck"


def _write_text_atomic(path: str, text: str) -> None:
    """Write *text* to *path* via a temp sibling + ``os.replace`` (atomic)."""
    directory = os.path.dirname(path) or "."
    fd, tmp = tempfile.mkstemp(dir=directory, prefix=".deckgen-", suffix=".tmp")
    try:
        with os.fdopen(fd, "w", encoding="utf-8") as fh:
            fh.write(text)
            fh.flush()
            os.fsync(fh.fileno())
        os.replace(tmp, path)
    except BaseException:
        try:
            os.unlink(tmp)
        except OSError:
            pass
        raise


def scaffold_deck(
    out_dir: str,
    slug: str,
    tex: str,
    *,
    overwrite: bool = False,
) -> dict:
    """Create ``<out_dir>/<slug>/`` with ``<slug>.tex`` + a ``Makefile``.

    Returns a dict with the written paths and ``sibling_common`` (whether
    *out_dir* contains a ``common/`` dir, so ``../common/...`` resolves from the
    project folder). Raises :class:`ScaffoldError` on unsafe input or an
    existing deck (unless *overwrite*).
    """
    if not _SAFE_SLUG_RE.match(slug or ""):
        raise ScaffoldError(
            f"Unsafe deck name {slug!r}: use letters, digits, '.', '_' or '-' only."
        )
    if not out_dir or not os.path.isdir(out_dir):
        raise ScaffoldError(f"Output directory does not exist: {out_dir!r}")

    out_abs = os.path.realpath(out_dir)
    project_dir = os.path.join(out_abs, slug)
    # The slug must not escape out_dir (defence in depth; _SAFE_SLUG_RE already
    # forbids slashes and a leading dot).
    if os.path.dirname(os.path.realpath(os.path.join(out_abs, slug))) != out_abs:
        raise ScaffoldError(f"Deck name {slug!r} would escape the output directory.")

    tex_path = os.path.join(project_dir, f"{slug}.tex")
    makefile_path = os.path.join(project_dir, "Makefile")

    if os.path.exists(tex_path) and not overwrite:
        raise ScaffoldError(
            f"A deck already exists at {tex_path!r}. Choose another name or "
            "enable overwrite."
        )

    try:
        os.makedirs(project_dir, exist_ok=True)
        _write_text_atomic(tex_path, tex if tex.endswith("\n") else tex + "\n")
        _write_text_atomic(makefile_path, _MAKEFILE_TEMPLATE.format(slug=slug))
    except OSError as exc:
        raise ScaffoldError(f"Could not write the deck folder: {exc}") from exc

    return {
        "project_dir": project_dir,
        "tex_path": tex_path,
        "makefile_path": makefile_path,
        "sibling_common": os.path.isdir(os.path.join(out_abs, "common")),
    }
