"""Write a generated deck into a compile-ready project folder.

Given the assembled ``.tex``, an output directory and a slug, create

    <out_dir>/<slug>/<slug>.tex
    <out_dir>/<slug>/Makefile        # DOC = <slug>; depth-independent suite-root walk-up

so the deck drops straight into the user's LaTeX suite and builds with ``make``.
This module stays app-independent (no project imports) — like the vendored audit
tree, it keeps its own atomic-write helper rather than importing ``core.utils``.
"""
from __future__ import annotations

import os
import re
import tempfile

# A deck folder/file name: letters, digits, and the safe separators. No slashes,
# no ``..`` — the slug names a single new child directory under out_dir.
_SLUG_RE = re.compile(r"[^A-Za-z0-9._-]+")
_SAFE_SLUG_RE = re.compile(r"\A[A-Za-z0-9][A-Za-z0-9._-]*\Z")

# The Makefile locates the suite's ``common/latex-build.mk`` by walking up the
# directory tree rather than hardcoding ``../common`` (one level). That bare
# ``../common`` only resolved when the deck sat exactly one level below the suite
# root; a deck under e.g. ``<suite>/cours/<slug>/`` would never find it. The
# walk-up is relative, space-safe, and depth-independent (matches the suite's own
# hand-maintained projects). The ``$$`` are LITERAL ``$`` for the shell — Make
# collapses ``$$`` → ``$`` and must NOT expand them itself; only ``$(shell …)``
# and ``$(SUITE_ROOT)`` are Make variable references (single ``$``).
_MAKEFILE_TEMPLATE = (
    "# Generated by deckgen. Build with:  make view   (or: make)\n"
    "# Everything else (targets, OS-aware viewer, dated PDFs) lives in\n"
    "# common/latex-build.mk. SUITE_ROOT is found by walking up the tree so the\n"
    "# deck builds from any depth under the suite root (not just one level down).\n"
    "DOC = {slug}\n"
    "SUITE_ROOT := $(shell d=.; n=0; "
    "while [ ! -e \"$$d/common/latex-build.mk\" ] && [ $$n -lt 12 ]; "
    "do d=$$d/..; n=$$((n+1)); done; echo \"$$d\")\n"
    "include $(SUITE_ROOT)/common/latex-build.mk\n"
)

# Mirror of the Makefile's walk-up: the relative marker that identifies the suite
# root, and the same depth bound (the Makefile loops while ``n < 12``).
_SUITE_MARKER = os.path.join("common", "latex-build.mk")
_SUITE_WALK_MAX_LEVELS = 12


def _find_suite_root(start_dir: str, *, max_levels: int = _SUITE_WALK_MAX_LEVELS) -> str:
    """Walk up from *start_dir* looking for ``common/latex-build.mk``.

    Mirrors the generated Makefile's depth-independent walk-up so the scaffold's
    advisory ("will the build find the suite?") matches what ``make`` will
    actually do. Returns the directory that contains ``common/latex-build.mk``,
    or ``""`` if none is found within *max_levels* parents.
    """
    directory = os.path.realpath(start_dir)
    for _ in range(max_levels + 1):
        if os.path.exists(os.path.join(directory, _SUITE_MARKER)):
            return directory
        parent = os.path.dirname(directory)
        if parent == directory:  # reached the filesystem root
            break
        directory = parent
    return ""


class ScaffoldError(RuntimeError):
    """Raised when the deck folder cannot be created safely."""


def slugify(text: str) -> str:
    """Filesystem-safe slug: ``[A-Za-z0-9._-]``, lower-cased, never empty."""
    slug = _SLUG_RE.sub("_", (text or "").strip()).strip("_.-").lower()
    return slug or "deck"


def _write_text_atomic(path: str, text: str) -> None:
    """Write *text* to *path* via a temp sibling + ``os.replace`` (atomic)."""
    directory = os.path.dirname(path) or "."
    fd, tmp = tempfile.mkstemp(dir=directory, prefix=".deckgen-", suffix=".tmp")
    try:
        with os.fdopen(fd, "w", encoding="utf-8") as fh:
            fh.write(text)
            fh.flush()
            os.fsync(fh.fileno())
        os.replace(tmp, path)
    except BaseException:
        try:
            os.unlink(tmp)
        except OSError:
            pass
        raise


def scaffold_deck(
    out_dir: str,
    slug: str,
    tex: str,
    *,
    overwrite: bool = False,
) -> dict:
    """Create ``<out_dir>/<slug>/`` with ``<slug>.tex`` + a ``Makefile``.

    Returns a dict with the written paths plus ``suite_root_found`` (whether the
    Makefile's walk-up will find ``common/latex-build.mk`` from the project
    folder) and ``suite_root`` (the resolved directory, or ``""``). Raises
    :class:`ScaffoldError` on unsafe input or an existing deck (unless
    *overwrite*).
    """
    if not _SAFE_SLUG_RE.match(slug or ""):
        raise ScaffoldError(
            f"Unsafe deck name {slug!r}: use letters, digits, '.', '_' or '-' only."
        )
    if not out_dir or not os.path.isdir(out_dir):
        raise ScaffoldError(f"Output directory does not exist: {out_dir!r}")

    out_abs = os.path.realpath(out_dir)
    project_dir = os.path.join(out_abs, slug)
    # The slug must not escape out_dir (defence in depth; _SAFE_SLUG_RE already
    # forbids slashes and a leading dot).
    if os.path.dirname(os.path.realpath(os.path.join(out_abs, slug))) != out_abs:
        raise ScaffoldError(f"Deck name {slug!r} would escape the output directory.")

    tex_path = os.path.join(project_dir, f"{slug}.tex")
    makefile_path = os.path.join(project_dir, "Makefile")

    if os.path.exists(tex_path) and not overwrite:
        raise ScaffoldError(
            f"A deck already exists at {tex_path!r}. Choose another name or "
            "enable overwrite."
        )

    try:
        os.makedirs(project_dir, exist_ok=True)
        _write_text_atomic(tex_path, tex if tex.endswith("\n") else tex + "\n")
        _write_text_atomic(makefile_path, _MAKEFILE_TEMPLATE.format(slug=slug))
    except OSError as exc:
        raise ScaffoldError(f"Could not write the deck folder: {exc}") from exc

    suite_root = _find_suite_root(project_dir)
    return {
        "project_dir": project_dir,
        "tex_path": tex_path,
        "makefile_path": makefile_path,
        "suite_root": suite_root,
        "suite_root_found": bool(suite_root),
    }


def write_deck_tex(out_dir: str, slug: str, tex: str) -> dict:
    """Overwrite ONLY ``<out_dir>/<slug>/<slug>.tex`` in place — no Makefile touch.

    Used by the apply-repair path. The deck folder + ``Makefile`` already exist
    from generation, and an integrity repair should change only the ``.tex``;
    rewriting the ``Makefile`` (as ``scaffold_deck(overwrite=True)`` does) would
    silently clobber any hand-edits the user made to it after generating. Validates
    the slug + the same no-escape rule as :func:`scaffold_deck`, and requires the
    deck's ``.tex`` to already exist (apply-repair only ever updates a generated
    deck). Returns ``{project_dir, tex_path}``.
    """
    if not _SAFE_SLUG_RE.match(slug or ""):
        raise ScaffoldError(
            f"Unsafe deck name {slug!r}: use letters, digits, '.', '_' or '-' only."
        )
    if not out_dir or not os.path.isdir(out_dir):
        raise ScaffoldError(f"Output directory does not exist: {out_dir!r}")

    out_abs = os.path.realpath(out_dir)
    project_dir = os.path.join(out_abs, slug)
    if os.path.dirname(os.path.realpath(os.path.join(out_abs, slug))) != out_abs:
        raise ScaffoldError(f"Deck name {slug!r} would escape the output directory.")

    tex_path = os.path.join(project_dir, f"{slug}.tex")
    if not os.path.isfile(tex_path):
        raise ScaffoldError(
            f"No existing deck to update at {tex_path!r}; generate it first."
        )
    try:
        _write_text_atomic(tex_path, tex if tex.endswith("\n") else tex + "\n")
    except OSError as exc:
        raise ScaffoldError(f"Could not write the deck .tex: {exc}") from exc

    return {"project_dir": project_dir, "tex_path": tex_path}


def write_deck_at(path: str, tex: str) -> dict:
    """Atomically overwrite an EXISTING deck ``.tex`` at *path* in place.

    Used by the augment apply path: unlike :func:`write_deck_tex` (which derives
    ``<out_dir>/<slug>/<slug>.tex`` from a scaffold layout), augment edits an
    arbitrary user-chosen deck — deckgen-made or hand-written — so it writes back
    to the exact file it read. The route is responsible for validating *path*
    (absolute, existing, ``.tex``, not a system location); this helper only re-checks
    that the file still exists and writes it atomically. Returns ``{tex_path}``.
    """
    if not path or not os.path.isfile(path):
        raise ScaffoldError(f"No existing deck to update at {path!r}.")
    try:
        _write_text_atomic(path, tex if tex.endswith("\n") else tex + "\n")
    except OSError as exc:
        raise ScaffoldError(f"Could not write the deck .tex: {exc}") from exc
    return {"tex_path": path}
